### PR TITLE
Added some slaps

### PR DESCRIPTION
**Pull request by Jereviendrai**
Please check for missing commata.

### CODE REVIEW

**Comment by ltobler** [comment]
Nice work, some escape characters missing though

**Comment by sgitkene** [comment]
Luke will test and fix if necessary.

**Comment by Jereviendrai** [comment]
Thank ya Luke~
Didn't feel like doing proper research on lua.

**Comment by ltobler** [comment]
It was fine i just disabled my brain for a second and forget which way around pattern matching works, gg

**Pull request merged**
